---

- name: Get RDS Facts
  rds:
    command: facts
    instance_name: "{{ instance_name }}"
    region: "{{ region }}"
  ignore_errors: true
  register: rds_database_facts

- name: Create Security Group if not defined
  ec2_group:
    name: "{{ instance_name }}"
    description: sg group for rds created by ansible
    vpc_id: "{{ vpc }}"
    region: "{{ region }}"
  register: sg
  when: vpc_security_groups==""

- name: Set New Security Group 
  set_fact:
    vpc_security_groups: "{{sg.group_id}}"
  when:	vpc_security_groups==""

- name: Create RDS
  rds:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    command: create
    backup_retention: "{{ backup_retention }}"
    region: "{{ region }}"
    wait: true
    wait_timeout: 1200
    db_engine: "{{ db_engine }}"
    size: "{{ db_size }}"
    instance_type: "{{ instance_type }}"
    username: "{{ db_username }}"
    password: "{{ db_password }}"
    db_name: "{{ db_name }}"
    port: "{{ rds_port }}"
    storage_encrypted: True
    kms_key_id: arn:aws:kms:us-east-1:123456789012:key/70c45553-ad2e-4a85-9f14-cfeb47555c33
    vpc_security_groups: "{{ vpc_security_groups }}"
    publicly_accessible: false
    multi_zone: "{{ multi_az }}"
    maint_window: "{{ maintenance_window }}"
    subnet: "{{ subnet }}"
    instance_name: "{{ instance_name }}"
    tags:
      Name: "{{ instance_name }}"
      value: "testing"
  register: rds
  when: rds_action=="provision"


  rds:
    command: snapshot
    instance_name: "{{ instance_name }}"
    snapshot: snapshot-rds
    encrypted: true
    kms_key_id: arn:aws:kms:us-east-1:123456789012:key/70c45553-ad2e-4a85-9f14-cfeb47555c33
    region: "{{region}}"
    
- rds:
    command: restore
    region: '{{ aws_region }}'
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    instance_name: '{{instance_name}}'
    snapshot: snapshot-rds
    db_engine: '{{ db_engine }}'
    iops: '1000'
    instance_type: '{{ instance_type }}'
    subnet: '{{ subnet }}'
    publicly_accessible: yes
    

